"""Reusable JAX helpers for the pizza-house bandit demo."""

from .pizza_bandit import (
    NormalInverseGammaPosterior,
    NormalInverseGammaPrior,
    SimulationResult,
    StudentTParams,
    SufficientStats,
    best_probabilities,
    initial_stats,
    mean_posterior_params,
    posterior_from_stats,
    predictive_params,
    probability_best_monte_carlo,
    probability_best_quadrature,
    sample_house_from_best_probability,
    sample_student_t,
    simulate_bandit,
    stats_from_observations,
    student_t_cdf,
    student_t_logpdf,
    student_t_pdf,
    uncertainty_decomposition,
    update_stats,
)

__all__ = [
    "NormalInverseGammaPosterior",
    "NormalInverseGammaPrior",
    "SimulationResult",
    "StudentTParams",
    "SufficientStats",
    "best_probabilities",
    "initial_stats",
    "mean_posterior_params",
    "posterior_from_stats",
    "predictive_params",
    "probability_best_monte_carlo",
    "probability_best_quadrature",
    "sample_house_from_best_probability",
    "sample_student_t",
    "simulate_bandit",
    "stats_from_observations",
    "student_t_cdf",
    "student_t_logpdf",
    "student_t_pdf",
    "uncertainty_decomposition",
    "update_stats",
]
